### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by virihonoris** [Akasiek/off-the-frame#26]
- [x] Aby nowo dodane produkty pojawiały się na górze.
	![Zrzut ekranu 2024-06-4 o 18 32 28](https://github.com/Akasiek/off-the-frame/assets/112962669/3fa96344-1a26-4f75-b1fa-28ba28307030)

- [x] Zamiast "previous" i "next" były tak jak w products by category liczby 
	![Zrzut ekranu 2024-06-4 o 18 33 26](https://github.com/Akasiek/off-the-frame/assets/112962669/f4f329dc-6ca5-42fa-9039-c152e2de82ab)

- [ ] Podczas dodawania Style Guide najlepiej jakby dało się dodawać produkty dzięki zdjęciom, tak samo podczas dodawania Outfit of the day
	![Zrzut ekranu 2024-06-4 o 18 35 25](https://github.com/Akasiek/off-the-frame/assets/112962669/6aef2860-8fa8-4355-b692-3701c9c0a961)

**Comment by Akasiek** [comment]
> Podczas dodawania Style Guide najlepiej jakby dało się dodawać produkty dzięki zdjęciom, tak samo podczas dodawania Outfit of the day

To raczej nie do zrobienia
