### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by virihonoris** [Akasiek/off-the-frame#28]
- [x]  Kategorie w kolejności:

Shoes
T-Shirts & Tops
Coats & Jackets
Knitwear
Hoodies & Sweatshirts
Trousers
Dresses
Skirts
Accessories
Jewelries

**Comment by Akasiek** [comment]
Nie ma czegoś takiego jak "Jewelries". Jest "Jewellery"

**Comment by virihonoris** [comment]
zmieniłem

**Comment by virihonoris** [comment]
zmieniłem
