### ISSUE TITLE
Products by category - subcategories

### ISSUE THREAD

**Issue by virihonoris** [Akasiek/off-the-frame#31]
- [x]  Między kategoriami a produktami dodać podkategorie. Defaultowo aby żadna podkategoria jak wchodzimy w kategorie nie była wybrana.

![Zrzut ekranu 2024-07-10 o 18 27 14](https://github.com/Akasiek/off-the-frame/assets/112962669/e731bc1f-86bf-47f7-a4c5-7d15e1105803)

Moim pomysłem jest to aby w dashboardzie dodać kolejną zakładkę z podkategoriami i jak tworzymy nową podkategorię to dodajemy ją pod jakąś kategorie.

**Comment by Akasiek** [comment]
Podaj mi wszystkie podkategorie jakie chcesz mieć w aplikacji na start. Będzie mi się lepiej testowało

**Comment by virihonoris** [comment]
W Jewellery:
Earrings, Necklaces, Rings

W Accessories:
Bags, Backpacks, Glasses, Belts, Socks, Warmers, Other

Moge podać narazie tylko w tych dwóch kategoriach? Bo w innych jeszcze dokładnie nie wiem

**Comment by Akasiek** [comment]
Może być. I tak będę musiał potestować jak działa kategoria bez podkategorii
